export enum OntologyBranch {
  DEVICES = "DEVICES",
  ACCOUNTS = "ACCOUNTS",
  APPS = "APPS",
  FILES = "FILES",
  CLOUD_STORAGE = "CLOUD_STORAGE",
  EMAIL = "EMAIL",
  CONTACTS = "CONTACTS",
  PAYMENTS_SUBSCRIPTIONS = "PAYMENTS_SUBSCRIPTIONS",
  SECURITY_ACCESS = "SECURITY_ACCESS",
  BACKUPS_ARCHIVES = "BACKUPS_ARCHIVES",
  UNKNOWN_NEEDS_REVIEW = "UNKNOWN_NEEDS_REVIEW"
}

export enum ObjectType {
  DEVICE = "DEVICE",
  ACCOUNT = "ACCOUNT",
  APP = "APP",
  FILE = "FILE",
  FOLDER = "FOLDER",
  BROWSER_PROFILE = "BROWSER_PROFILE",
  SUBSCRIPTION = "SUBSCRIPTION",
  CREDENTIAL_REFERENCE = "CREDENTIAL_REFERENCE",
  SESSION_OR_TOKEN_REFERENCE = "SESSION_OR_TOKEN_REFERENCE",
  RECOVERY_METHOD = "RECOVERY_METHOD",
  BACKUP_OR_ARCHIVE = "BACKUP_OR_ARCHIVE",
  PAYMENT_SOURCE = "PAYMENT_SOURCE",
  CLOUD_CONTAINER = "CLOUD_CONTAINER",
  UNKNOWN_OBJECT = "UNKNOWN_OBJECT"
}

export enum RelationshipType {
  OWNS = "OWNS",
  CONTAINS = "CONTAINS",
  AUTHENTICATES = "AUTHENTICATES",
  RECOVERS = "RECOVERS",
  BILLS = "BILLS",
  SYNCS = "SYNCS",
  DEPENDS_ON = "DEPENDS_ON",
  DUPLICATES = "DUPLICATES",
  BACKS_UP = "BACKS_UP",
  LINKED_TO = "LINKED_TO",
  INSTALLED_ON = "INSTALLED_ON",
  EXPORTED_FROM = "EXPORTED_FROM",
  IMPORTED_TO = "IMPORTED_TO",
  SHARED_WITH = "SHARED_WITH",
  UNKNOWN_RELATION = "UNKNOWN_RELATION"
}

export enum Confidence {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH"
}

export enum EvidenceOriginType {
  OBSERVED = "OBSERVED",
  INFERRED = "INFERRED"
}

export enum Sensitivity {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL"
}

export enum Risk {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL"
}

export enum ObjectState {
  DISCOVERED = "DISCOVERED",
  NORMALIZED = "NORMALIZED",
  NEEDS_REVIEW = "NEEDS_REVIEW",
  READY = "READY",
  BLOCKED = "BLOCKED"
}

export enum ReviewState {
  UNREVIEWED = "UNREVIEWED",
  IN_REVIEW = "IN_REVIEW",
  REVIEWED = "REVIEWED",
  REJECTED = "REJECTED"
}

export enum PreserveState {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  PRESERVED = "PRESERVED",
  FAILED = "FAILED"
}

export enum VerificationState {
  NOT_VERIFIED = "NOT_VERIFIED",
  IN_PROGRESS = "IN_PROGRESS",
  VERIFIED = "VERIFIED",
  PARTIAL = "PARTIAL",
  FAILED = "FAILED",
  NOT_VERIFIABLE = "NOT_VERIFIABLE"
}

export enum WorkflowType {
  DISCOVERY = "DISCOVERY",
  PRESERVATION = "PRESERVATION",
  READINESS = "READINESS",
  EXECUTION = "EXECUTION",
  REPORTING = "REPORTING"
}

export enum WorkflowState {
  PENDING = "PENDING",
  RUNNING = "RUNNING",
  BLOCKED = "BLOCKED",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  PARTIAL = "PARTIAL"
}

export enum TaskType {
  DISCOVER = "DISCOVER",
  CLASSIFY = "CLASSIFY",
  PRESERVE = "PRESERVE",
  EVALUATE_POLICY = "EVALUATE_POLICY",
  APPROVE = "APPROVE",
  VERIFY = "VERIFY"
}

export enum TaskState {
  PENDING = "PENDING",
  RUNNING = "RUNNING",
  BLOCKED = "BLOCKED",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  PARTIAL = "PARTIAL"
}

export enum FailureCategory {
  VALIDATION = "VALIDATION",
  POLICY = "POLICY",
  EXTERNAL = "EXTERNAL",
  INTERNAL = "INTERNAL"
}

export enum BlockReason {
  POLICY_BLOCK = "POLICY_BLOCK",
  APPROVAL_REQUIRED = "APPROVAL_REQUIRED",
  MISSING_EVIDENCE = "MISSING_EVIDENCE",
  DEPENDENCY_UNRESOLVED = "DEPENDENCY_UNRESOLVED"
}

export enum ActionClass {
  READ = "READ",
  PRESERVE = "PRESERVE",
  SIMULATE = "SIMULATE",
  EXECUTE = "EXECUTE",
  VERIFY = "VERIFY"
}

export enum PolicyDecisionResult {
  ALLOW = "ALLOW",
  DENY = "DENY",
  REQUIRE_APPROVAL = "REQUIRE_APPROVAL"
}

export enum ApprovalType {
  EXECUTION = "EXECUTION",
  POLICY_EXCEPTION = "POLICY_EXCEPTION"
}

export enum ApprovalState {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED"
}

export enum TrustProfile {
  STRICT = "STRICT",
  BALANCED = "BALANCED",
  PERMISSIVE = "PERMISSIVE"
}
