export enum ObjectType {
  DEVICE = "DEVICE",
  ACCOUNT = "ACCOUNT",
  APP = "APP",
  FILE = "FILE",
  CLOUD_STORAGE = "CLOUD_STORAGE",
  EMAIL = "EMAIL",
  CONTACT = "CONTACT",
  PAYMENT_SUBSCRIPTION = "PAYMENT_SUBSCRIPTION",
  SECURITY_ACCESS = "SECURITY_ACCESS",
  BACKUP_ARCHIVE = "BACKUP_ARCHIVE",
  UNKNOWN_REVIEW = "UNKNOWN_REVIEW"
}

export enum RelationshipType {
  OWNS = "OWNS",
  USES = "USES",
  CONNECTED_TO = "CONNECTED_TO",
  DEPENDS_ON = "DEPENDS_ON",
  STORED_IN = "STORED_IN",
  AUTHENTICATES_WITH = "AUTHENTICATES_WITH"
}

export enum Confidence {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH"
}

export enum Sensitivity {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL"
}

export enum Risk {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL"
}

export enum ObjectState {
  DISCOVERED = "DISCOVERED",
  NORMALIZED = "NORMALIZED",
  NEEDS_REVIEW = "NEEDS_REVIEW",
  READY = "READY",
  BLOCKED = "BLOCKED"
}

export enum ReviewState {
  UNREVIEWED = "UNREVIEWED",
  IN_REVIEW = "IN_REVIEW",
  REVIEWED = "REVIEWED",
  REJECTED = "REJECTED"
}

export enum PreserveState {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  PRESERVED = "PRESERVED",
  FAILED = "FAILED"
}

export enum VerificationState {
  NOT_VERIFIED = "NOT_VERIFIED",
  IN_PROGRESS = "IN_PROGRESS",
  VERIFIED = "VERIFIED",
  PARTIAL = "PARTIAL",
  FAILED = "FAILED",
  NOT_VERIFIABLE = "NOT_VERIFIABLE"
}

export enum WorkflowType {
  DISCOVERY = "DISCOVERY",
  PRESERVATION = "PRESERVATION",
  READINESS = "READINESS",
  EXECUTION = "EXECUTION",
  REPORTING = "REPORTING"
}

export enum WorkflowState {
  PENDING = "PENDING",
  RUNNING = "RUNNING",
  BLOCKED = "BLOCKED",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  PARTIAL = "PARTIAL"
}

export enum TaskType {
  DISCOVER = "DISCOVER",
  CLASSIFY = "CLASSIFY",
  PRESERVE = "PRESERVE",
  EVALUATE_POLICY = "EVALUATE_POLICY",
  APPROVE = "APPROVE",
  VERIFY = "VERIFY"
}

export enum TaskState {
  PENDING = "PENDING",
  RUNNING = "RUNNING",
  BLOCKED = "BLOCKED",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  PARTIAL = "PARTIAL"
}

export enum FailureCategory {
  VALIDATION = "VALIDATION",
  POLICY = "POLICY",
  EXTERNAL = "EXTERNAL",
  INTERNAL = "INTERNAL"
}

export enum BlockReason {
  POLICY_BLOCK = "POLICY_BLOCK",
  APPROVAL_REQUIRED = "APPROVAL_REQUIRED",
  MISSING_EVIDENCE = "MISSING_EVIDENCE",
  DEPENDENCY_UNRESOLVED = "DEPENDENCY_UNRESOLVED"
}

export enum ActionClass {
  READ = "READ",
  PRESERVE = "PRESERVE",
  SIMULATE = "SIMULATE",
  EXECUTE = "EXECUTE",
  VERIFY = "VERIFY"
}

export enum PolicyDecisionResult {
  ALLOW = "ALLOW",
  DENY = "DENY",
  REQUIRE_APPROVAL = "REQUIRE_APPROVAL"
}

export enum ApprovalType {
  EXECUTION = "EXECUTION",
  POLICY_EXCEPTION = "POLICY_EXCEPTION"
}

export enum ApprovalState {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED"
}

export enum TrustProfile {
  STRICT = "STRICT",
  BALANCED = "BALANCED",
  PERMISSIVE = "PERMISSIVE"
}
